/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "switch_1_aliases.h"
#include "switch_1.h"
#include "lcd_char_1.h"
#include "quaddec_1.h"
#include "quaddec_1_PVT.h"
#include "c1_aliases.h"
#include "c1.h"
#include "c2_aliases.h"
#include "c2.h"
#include "Clock_1.h"
#include "ADC_SAR_Seq_1.h"
#include "analog_1_aliases.h"
#include "analog_1.h"
#include "lcd_char_1_LCDPort_aliases.h"
#include "lcd_char_1_LCDPort.h"
#include "quaddec_1_isr.h"
#include "quaddec_1_Cnt16.h"
#include "ADC_SAR_Seq_1_SAR.h"
#include "ADC_SAR_Seq_1_IntClock.h"
#include "ADC_SAR_Seq_1_TempBuf_dma.h"
#include "ADC_SAR_Seq_1_FinalBuf_dma.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

